apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - postgres.yaml
  - minio.yaml
  - services.yaml
  - migrations.yaml
  - s3-csi.yaml
  - s3-csi-rbac-fix.yaml

configMapGenerator:
  - name: users-migrations
    namespace: messager
    files:
      - migrations/users/001_init.sql

  - name: messages-migrations
    namespace: messager
    files:
      - migrations/messages/001_init.sql
      - migrations/messages/002_add_file_name.sql

generatorOptions:
  disableNameSuffixHash: true
